# This main.yml should be put in Github Action dir: .github/workflows/main.yml
# It does auto unzip files, auto deploy to Heroku, auto upload/sync FTP
# Those like ${{secrets.FTP_SERVER_ADDRESS}}, are env var of Github repository's Setting > Serect

# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Unzip and remove zip files
      - run: unzip -qq './data/*.zip' -d ./data && rm ./data/*.zip
      # Deploy to Heroku
      - uses: akhileshns/heroku-deploy@v3.7.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}} #Must be unique in Heroku
          heroku_email: ${{secrets.EMAIL_ADDRESS}}

      # 📂 FPT Sync files
      - uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{secrets.FTP_SERVER_ADDRESS}}
          username: ${{secrets.FTP_USERNAME}}
          password: ${{secrets.FTP_PASSWORD}}
          # Be mindful the server-dir, must provide correctly
          server-dir: ${{secrets.FTP_SERVER_DIR}}

